# baseurl: "/My-ITSM-Journey" 
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme
theme: minima
title: Gusti Gratia Delpiera
description: Welcome to my IT Service Management (ITSM) journey! Think of it as my digital 'home,' where I share my progress and growth throughout this course. This journey is a collection of all the assignments, labs, reflections, and projects I've completed over the semester. Each milestone represents a 'room' in my house, reflecting a different aspect of my development in the world of IT Service Management.
paginate: 5
